name: CI

on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
 conviso-ast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli
     env:
       CONVISO_API_KEY:  ${{secrets.CONVISO_API_KEY}}
   steps:
   - uses: actions/checkout@v4

   - name: Run AST
     run: conviso sca run --asset-name "Vulnerable-Web-Application" --company-id 843
